### ISSUE TITLE
Expire in the Add portal is not there

### ISSUE THREAD

**Issue by mwahal** [Chris230291/STB-Proxy#12]
There is no way to add anything under the expire column in the portal Add section. And because of that, the code fails.

```
  File "app.py", line 146, in add
    portals.append({"name": name, "url": url, "mac": mac, "proxy": proxy, "format": format, "expires": getExpires(
  File "app.py", line 103, in getExpires
    return expire
UnboundLocalError: local variable 'expire' referenced before assignment
```

![image](https://user-images.githubusercontent.com/749082/134430655-149f2581-7210-481b-9d96-f3c5bf435b2c.png)

**Comment by mwahal** [comment]
Found the issue...
app.py line 102 has incorrect assignment.

```python
        expires = "?"
```

It should be 
```python
        expire = "?"
```

**Comment by Chris230291** [comment]
I spotted that myself today when I was reworking some of the functions. Thanks
