### ISSUE TITLE
is it possible to get the VOD m3u?

### ISSUE THREAD

**Issue by Tck13** [Chris230291/STB-Proxy#26]
> Yes and no. Unless somebody knows the URL to get all vods in one request I would have to get each "page" individually, which is about 14 vods at a time. Since a lot of servers have 500 pages or sometimes many more, that is a lot of requests to make which takes minutes to complete. If I run them all in parallel I found some providers would ban me.
> 
> Without knowing all of the different portal requests (I only know the ones other apps use by looking at wireshark), its difficult to know what the options are.
> 
> I can rework things like the webui so that each page, search etc is a separate request, but remember I am not a programmer and it looked way more complicated. I'd rather keep it as simple as possible. Besides that would be a lot of work and I don't care for vods.
>
>_Originally posted by @Chris230291 in https://github.com/Chris230291/STB-Proxy/issues/18#issuecomment-966408288_
 
It seems to be the right way to go though, a Kodi plugin written in Python that adds the ability to watch IPTV from MAC address based providers (Stalker Middleware) also goes through all the pages for VOD;

https://github.com/kens13/Kens13_Repo/blob/943d733cc1e228c5046f7e06556ce26d686667e0/Addons/plugin.video.IPTVXtra/stalker.py#L394

I also don't come across anything like a "get_all_channels" for VOD online.... The webpage below gives a lot of examples of requests & answers that can be sent; 

https://www.quassi.nl/2020/03/23/the-wonderful-world-of-stalker-iptv-2

Hope that with both links I have helped you further with the goal of STB proxy to be a complete STB portal -> m3u proxy, I must agree with you there is limited explanation online about how the communication works 🙂

**Comment by Chris230291** [comment]
I am wary about this. I got banned from one provider because I tried to get all "pages" concurrently ( I think the concurrent futures module I was using defaults to 1 request per CPU core).

I could do it slowly one at a time and cache the results. But then how often should I rebuild the cache? It takes some time to make 100s or 1000s of http requests... very long if the server is slow to respond.

I imagine the VOD playlist being completely separate from the live playlist and with no customization. Perhaps there could be a 3rd playlist that's both combined.

What would you expect?

**Comment by Tck13** [comment]
VOD content doesn't change too often I think, so rebuilding the cache once a day sounds good. It may be happening in the background, somewhere in the web interface a progress bar would be great 😉

Possibly make a configurable delay, as Kodi seems to be without any real delay and I think that works fine 😕

VOD playlist can indeed be a completely separate playlist because live TV is something else.

**Comment by Chris230291** [comment]
Is there a special m3u format for VODs?
Some TV shows might have hundreds of episodes... That will be a massive list in clients (crash?) if there isn't a special format that nests shows/seasons/episodes.

**Comment by CyberPoison** [comment]
https://github.com/kens13/Kens13_Repo/blob/943d733cc1e228c5046f7e06556ce26d686667e0/Addons/plugin.video.IPTVXtra/stalker.py#L408

Don't like this way, i rather  prefer a while loop in that case since data is empty at the last page.

**Comment by CyberPoison** [comment]
His methods seem good, https://github.com/kens13/Kens13_Repo/blob/943d733cc1e228c5046f7e06556ce26d686667e0/Addons/plugin.video.IPTVXtra/stalker.py#L381
