### ISSUE TITLE
Fallback channel

### ISSUE THREAD

**Issue by 3v3rm4rt3lL** [Chris230291/STB-Proxy#27]
Could be possible activate a fallback channel when url main stream get 401 code or 503  code? 
Thanks.

**Comment by Chris230291** [comment]
Does this not happen?
To be clear STB-Proxy doesn't detect when a stream goes down mid-stream, it tests and switches source when the client first makes the request. Most clients will re-request as soon as a stream drops. In apps like VLC you can turn on the repeat option.

**Comment by 3v3rm4rt3lL** [comment]
> 

You right, I just notice that it plays the fallback channel after failed 5 times in VLC
