### ISSUE TITLE
Can the proxy run on a Raspberry Pi and/or on a decoder?

### ISSUE THREAD

**Issue by Gillonz** [Chris230291/STB-Proxy#30]
I'm struggling with docker on my raspberry pi to run the program: 
"WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error"
Is it me that hasn't yet understood how docker works, or it just can't work on arm?
Thanks

**Comment by Chris230291** [comment]
Hi. This container is only built for linux/amd64.
I think you would need to build the image yourself on the pi.

 `docker build -t <give name, eg: "chris/stb-proxy:latest"> https://github.com/Chris230291/STB-Proxy.git`

**Comment by Gillonz** [comment]
> docker build -t <give name, eg: "chris/stb-proxy:latest"> https://github.com/Chris230291/STB-Proxy.git

Thank you ! I am trying but I haven't managed yet to make it work. Thanks to your help I am learning something new, if I succed I will tell you. It would be very cool to have it working on a raspberry and have it 24h active without the need of a pc.
