### ISSUE TITLE
MAC lock in feature 

### ISSUE THREAD

**Issue by rockydares** [Chris230291/STB-Proxy#34]
Sometimes even if I've stopped watching but the dashboard says mac is still occupied. If I have single mac id then it's hard to stream on another device.

It would be easier if we had a choice to 'lock in' mac for single stream.

![Screenshot_2022-07-21-19-00-54-680_com brave browser~2](https://user-images.githubusercontent.com/66517282/180227468-7f11e126-d72e-4de3-82d0-85deb0cd844b.jpg)

**Comment by Chris230291** [comment]
Do you know how to reproduce this?
Id rather fix whatever causes it than add on more settings.

**Comment by CyberPoison** [comment]
Allowing to stream in multiple device should be allowed perhaps, so we could use the same playlist in multiple devices.

**Comment by Chris230291** [comment]
Added option to set streams per MAC
