### ISSUE TITLE
M3U playlist instead of MAC

### ISSUE THREAD

**Issue by 3v3rm4rt3lL** [Chris230291/STB-Proxy#41]
Hello, is possible to have something similar but instead of use MAC Address, we can use m3u playlist but sometimes provider only allow 1 connection and use fallback channel with ffmpeg to decide which line is free to tuner?. Thanks.

**Comment by Chris230291** [comment]
That is not something that I am interested in.
I think there are other tools available that do exactly what you want (merge and edit playlists and set backup channels).
I know some of them were paid but there might be a free solution too.

**Comment by 3v3rm4rt3lL** [comment]
Thank you. TVH is right just that I need. Cheers.

**Comment by 3v3rm4rt3lL** [comment]
I possible to have something to filter by categories?, I noticed when the iptv providers have like "100 stream" the playlist and when you play stream is very fast and responsive.  Thanks.
