### ISSUE TITLE
Playlist editor lags out on very large playlist

### ISSUE THREAD

**Issue by lindoalex577** [Chris230291/STB-Proxy#44]
Browsing the playlist editor in the browser lags out with portals that has thousands of channels in it. Also affects searching and exporting the playlist (not so much on playlist export, but still).

**Comment by Chris230291** [comment]
I think it depends a lot on the server you are running and the device you use to view it.
Once the initial page is loaded its all on your browser.

**Comment by sbeimel** [comment]
same issue here... looks like script cant handle very big playlists if you show 1000 channels or more browser will freeze

rehost/restream function will be nice as well

**Comment by Chris230291** [comment]
My PC can easily handle significantly more than 1000 channels and its over 10 years old.
The portal I am using has 2,723 channels, the page loads in ~4 seconds and searches etc are instant.

**Comment by Chris230291** [comment]
I will try changing how the table is drawn to see if it improves performance for you. No promises though.

**Comment by sbeimel** [comment]
Hi works now faster thanks for it. My Provider habe 11k Channels but i cant select „all“ it directly Crash could you take a Look on it again ?

**Comment by Chris230291** [comment]
When you select all here it crashes?

![image](https://user-images.githubusercontent.com/5328818/218286307-57d104de-0180-4b4f-9dad-bf391ad9b7c6.png)

If so this is because your browser/device just cant handle loading all at once.

**Comment by sbeimel** [comment]
Exactly it cant handle 11k lines 
Could you maybe add steps like 200,500,1000? And maybe additional Filter for „Provider“?

**Comment by Chris230291** [comment]
OK

**Comment by sbeimel** [comment]
Found another problem with big Playlists:
11k channels and „use channel genre“ error in playlist creation
If I set this setting off works again but without genre

**Comment by Chris230291** [comment]
fixed

**Comment by sbeimel** [comment]
Thx u are really quick :)
If a Mac is expired is it possible to remove them or sort to end ?
at the moment if the first Mac is expired it wil be used anyway. It won’t be skipped

**Comment by Chris230291** [comment]
The problem is that some providers do not use the expire variable correctly.
I have tried "expired" MACs that have worked.
So I leave it up to the user to remove dead MACs.

What you can do is enable `Try All MACs`. This will try all until one works.

At the moment I shuffle MACs before each request.
This means that if the first MAC is "bad", the next request from the client is likely to get another MAC, even with `Try All MACs` disabled.

**Comment by sbeimel** [comment]
Ok Never heard sth like this. For me Problem is I got a stream with info „expired“ so tool don’t use next Mac. Maybe possible to add a setting like skip Mac on expired ? Everybody can decide

**Comment by sbeimel** [comment]
push
