### ISSUE TITLE
Http proxy With auth support

### ISSUE THREAD

**Issue by sbeimel** [Chris230291/STB-Proxy#45]
Hi any Chance to add support for Proxy With user:pass ?

how is it working exactly cant find a doku 

lets say eG 1
One Portal 3 macs. How to use for each Mac 11 Stream With 3 proxy

eg2
More macs than proxy use them twice and local ip ?

**Comment by Chris230291** [comment]
Typically this is how you use credentials in a URL `http://username:password@example.com/`
Whether your proxy/proxy software supports this I do not know.

Balancing between multiple proxies... I'm not sure I want put in the work to do that.

Maybe you can use some kind of external tool to balance connections between different proxies. I do not know of any but maybe they exist.

**Comment by sbeimel** [comment]
Thx for reply so i add http://username:password@example.com:Port in Proxy Field? 2 proxy like http://username:password@example.com:Port,http://username:password@example2.com:Port

**Comment by Chris230291** [comment]
html proxies only.
I use [gluetun](https://github.com/qdm12/gluetun) to connect to providers and convert to html proxies
