### ISSUE TITLE
Format or MIME Type not found

### ISSUE THREAD

**Issue by azertypwd** [Chris230291/STB-Proxy#48]
Hello,

After configuring my portal and my MAC, I don't know how to read the content of my channels.

Can you help me, I am a complete beginner.

My next goal is to connect by plex on the STB-proxy.

But I can't read the content via the web page

![image](https://user-images.githubusercontent.com/45259791/225174945-efc1c9db-f172-44e4-b499-d06f710f04bb.png)

**Comment by Chris230291** [comment]
Which browser and device are you using?
I know web playback doesn't work on all browsers/devices.
The play button in the web UI is meant to be for testing streams rather than a way to watch.

**Comment by azertypwd** [comment]
for reading I tried on Windows and Linux,

No problem for the web player but I wanted to do the test with VLC before the Plex integration but on both OS I have this result.

![image](https://user-images.githubusercontent.com/45259791/225262958-0823a661-f860-4278-930c-acd22a9ee3b2.png)

Is it normal ?

**Comment by azertypwd** [comment]
I found the source of my problem in fact the reading errors occur because STB-Proxy interprets channel bundles as a channel.


For single channels it works fine.

I am interested in your advice concerning this problem about Channel bundles.

Thanks for your great job :)

**Comment by azertypwd** [comment]
I am also interested to know if it is possible to watch the video stream from plex, with several accounts at the same time.
Thanks

**Comment by Chris230291** [comment]
Some providers have channels that act as group titles. Normally they show a looping image/video like you show above. Don't enable those channels if you do not want to see them.

You can set the number of tuners available to Plex in the settings screen. Your portal should also support that many streams or you can add multiple MAC's to allow multiple streams.
