### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by rockydares** [Chris230291/STB-Proxy#5]
Previous script was working fine. New script gives this error while trying to run locally (not docker).

`Traceback (most recent call last):
  File "app.py", line 33, in <module>
    retries = Retry(total=5, backoff_factor=0.2, status_forcelist=[500, 502, 503, 504], allowed_m
ods=frozenset(['GET', 'POST']))
TypeError: __init__() got an unexpected keyword argument 'allowed_methods'`

**Comment by Chris230291** [comment]
It seems you are running an older version of requests or urllib3 (which is normally built in to python package).
If this didn't happen before, I think its because I had a typo which meant this option wasn't used before.

**Comment by kettenbach-it** [comment]
@Chris230291 You should a requirements.txt file in the repo. You can create this with "pip freeze >requirements.txt "

**Comment by kettenbach-it** [comment]
Please accept PR #10 for a requirements.txt

The requirements.txt needs to be updated on every new package installed with "pip install" with the command
```
pip freeze > requirements.txt
```
