### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by theshivamsharma-code** [Chris230291/STB-Proxy#53]
![brave_HNGabato4L](https://github.com/Chris230291/STB-Proxy/assets/75772986/8d98b49d-eec0-4b10-92a4-6068f2670a8b)

I will provide if you need anything

**Comment by Chris230291** [comment]
If no settings exist an new one is created like this

```
{
    "portals": {},
    "settings": {
        "stream method": "ffmpeg",
        "ffmpeg command": "ffmpeg -re -http_proxy <proxy> -timeout <timeout> -i <url> -map 0 -codec copy -f mpegts pipe:",
        "ffmpeg timeout": "5",
        "test streams": "true",
        "try all macs": "false",
        "use channel genres": "true",
        "use channel numbers": "true",
        "sort playlist by channel genre": "false",
        "sort playlist by channel number": "false",
        "sort playlist by channel name": "false",
        "enable security": "false",
        "username": "admin",
        "password": "12345",
        "enable hdhr": "false",
        "hdhr name": "STB-Proxy",
        "hdhr id": "48c81bcc3eb7464f8852f5da26b9d766",
        "hdhr tuners": "1"
    }
}
```
The file is read once and saved on start up. After that it only gets written to when you make any changes.

**Comment by theshivamsharma-code** [comment]
How can I convert this config.json to environment variables.I think server not able to read this config file

**Comment by Chris230291** [comment]
Docker is the only supported way of running this.
But it will also run in windows as long as dependencies are met.
Make sure you cd into the root directory of the project before you try to start app.py.

**Comment by Eldon1411** [comment]
can you make iptv server for me ?

**Comment by theshivamsharma-code** [comment]
I am trying to add one portal but showing an error.Can you check,I will send you the credentials to your email.
