### ISSUE TITLE
Problems with Plex channel / EPG ID length

### ISSUE THREAD

**Issue by raclo** [Chris230291/STB-Proxy#55]
Using STBPROXY as HDHomeRun with Plex have problems with EPG ID / channel id which is 38 characters, this causes the inability to manage favorite channels preventing them from being added or removed. (look at the attached images, the heart symbol is not visible for channels coming from STBProxy)
Another problem to report is in playback which both from PLEX and directly from the STBPROXY web interface often interrupts the streaming while for the same MAC from application like SFVIP the streaming has no interruptions. I tried modifying FFMpeg Command by adding
  -drop_pkts_on_overflow 1 -attempt_recovery 1 -recovery_wait_time 1 -attempt_recovery bool 1 -max_recovery_attempts 0 but nothing changes
![STBProxy Source](https://github.com/Chris230291/STB-Proxy/assets/26572084/51f5affb-5fcc-4cd7-a89b-ab09a034992a)
![Other source LiveTV](https://github.com/Chris230291/STB-Proxy/assets/26572084/a3341f39-b18c-450a-88c2-1ff4b1c990cd)
Any idea to fix this proble? Is there a way to set a parameter to always repeat playback? thanks for your attention.

**Comment by Chris230291** [comment]
I'm not sure why that happens in Plex. It appears to only be in the web app.

The replay feature is something you need to do on the client side.
My app reauthenticates with each new request so it will always take a bit longer to load a stream than other apps.
Some servers respond very quick though and cuts are almost unnoticeable even with my app.
Really the best solution is to use a better server and/or not use stolen accounts.
