### ISSUE TITLE
Cannot understand how the fallback channel works

### ISSUE THREAD

**Issue by LordKubaya** [Chris230291/STB-Proxy#59]
I don't understand what to put in the fallback, if is the name, id or number of the channel
also does it works for other portal? If all the macs from one portal become full can it change to other protal with  the macs for that portal?

**Comment by Chris230291** [comment]
It needs to be the same channel name. It works across all portals.

**Comment by LordKubaya** [comment]
Thank you for the response.

If it recognizes a fallback channel will it appear in the fallback column of the channel?

Also dos it needs to be switch on to work? This because I don't want to have 2 or of the same channel in my m3u playlist.

**Comment by Chris230291** [comment]
It is all done manually by the user.
Here is example.

![image](https://github.com/Chris230291/STB-Proxy/assets/5328818/95b660a5-d5a1-4db7-90c2-f4e655ebce20)
