### ISSUE TITLE
Please upload to docker the old version!!!

### ISSUE THREAD

**Issue by Tracker997** [Chris230291/STB-Proxy#9]
The new version doesn't work for me... :(

**Comment by Chris230291** [comment]
OK `chris230291/stb-proxy:old`
What is the problem with the new version?

**Comment by Tracker997** [comment]
Creates the channel list and none loads.

**Comment by Chris230291** [comment]
The new version is different. You need to re config. After adding a portal you must enable channels (all off by default) then hit save. Then playlist will have channels.

**Comment by Tracker997** [comment]
So i did and when i put the list in vlc player the channels don't start and start with the old STB proxy :)
